"""empty message

Revision ID: 225eb9d17adc
Revises: ddd69e0393d2
Create Date: 2020-08-18 18:03:24.838100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '225eb9d17adc'
down_revision = 'ddd69e0393d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('followers', 'follower',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('followers', 'parentId',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('tweets', 'userId',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tweets', 'userId',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('followers', 'parentId',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('followers', 'follower',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
