"""empty message

Revision ID: fefa2a6c2707
Revises: 
Create Date: 2020-08-18 13:42:19.178705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fefa2a6c2707'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('userTag', sa.String(length=200), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('mobile', sa.String(length=14), nullable=True),
    sa.Column('tweetCount', sa.Integer(), nullable=True),
    sa.Column('followingCount', sa.Integer(), nullable=True),
    sa.Column('followersCount', sa.Integer(), nullable=True),
    sa.Column('joined', sa.DateTime(), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(length=4294000000), nullable=True),
    sa.Column('profileImgUrl', sa.Text(length=42940000), nullable=True),
    sa.Column('posterImgUrl', sa.Text(length=42940000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('userTag')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
