export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";

export const GET_USER_TWEETS_REQUEST = "GET_USER_TWEETS_REQUEST";
export const GET_USER_TWEETS_SUCCESS = "GET_USER_TWEETS_SUCCESS";
export const GET_USER_TWEETS_FAILURE = "GET_USER_TWEETS_FAILURE";

export const GET_ALL_PROFILES_REQUEST = "GET_ALL_PROFILES_REQUEST";
export const GET_ALL_PROFILES_SUCCESS = "GET_ALL_PROFILES_SUCCESS";
export const GET_ALL_PROFILES_FAILURE = "GET_ALL_PROFILES_FAILURE";

export const FOLLOW_USER_REQUEST = "FOLLOW_USER_REQUEST";
export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS";
export const FOLLOW_USER_FAILURE = "FOLLOW_USER_FAILURE";

export const UN_FOLLOW_USER_REQUEST = "UN_FOLLOW_USER_REQUEST";
export const UN_FOLLOW_USER_SUCCESS = "UN_FOLLOW_USER_SUCCESS";
export const UN_FOLLOW_USER_FAILURE = "UN_FOLLOW_USER_FAILURE";

export const SELF_LIKE_TWEET_REQUEST = "SELF_LIKE_TWEET_REQUEST";
export const SELF_LIKE_TWEET_SUCCESS = "SELF_LIKE_TWEET_SUCCESS";
export const SELF_LIKE_TWEET_FAILURE = "SELF_LIKE_TWEET_FAILURE";